Models/ErrorViewModel.cs
namespace shoppingstore.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/AboutController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using shoppingstore.Models;

namespace shoppingstore.Controllers;

public class AboutController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/ContactController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using shoppingstore.Models;

namespace shoppingstore.Controllers;

public class ContactController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
    public RedirectResult Instagram(){
        return Redirect("https://www.instagram.com/");
    }
    public RedirectResult FaceBook(){
        return Redirect("https://www.facebook.com/");
    }
    public RedirectResult Twitter(){
        return Redirect("https://twitter.com/");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using shoppingstore.Models;

namespace shoppingstore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProductsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using shoppingstore.Models;

namespace shoppingstore.Controllers;

public class ProductsController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Views/About/index.cshtml
<h1 style="align-content:center ;">About Us</h1><hr>
<br>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
    when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
    It has survived not only five centuries, but also the leap into electronic typesetting,
    remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset 
    sheets containing Lorem Ipsum passages, and more recently with desktop publishing software
    like Aldus PageMaker including versions of Lorem Ipsum.</p>

Views/Contact/index.cshtml
<h1 style="text-align:center ;">Contact Us</h1><hr><br>
<form style="text-align: center;">
  <label for="fname">First name:</label>
  <input type="text" id="fname" name="fname" value="ABC"><br><br>
  <label for="lname">Last name:</label>
  <input type="text" id="lname" name="lname" value="D"><br><br>
  <input type="button" value="Submit">
</form>

Views/Home/index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome User to Our Online Shopping Store</h1><hr>
    <br>
    
</div>

Views/Products/index.cshtml
<h1 style="text-align:center">Products</h1><hr>
<dl style="text-align: center;">
  <dt>Coffee</dt>
  <dd>- black hot drink</dd>
  <dt>Milk</dt>
  <dd>- white cold drink</dd>
</dl>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - shoppingstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/shoppingstore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="_Layout.cshtml.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">shoppingstore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About US</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact US</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a asp-area="" asp-controller="Contact" asp-action="Instagram">Instagram</a>
            <a asp-area="" asp-controller="Contact" asp-action="FaceBook">FaceBook</a>
            <a asp-area="" asp-controller="Contact" asp-action="Twitter">Twitter</a>
            
            &copy; 2022 - Online_Shopping 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>